name: Training

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
  
    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - uses: iterative/setup-dvc@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          pip install -r requirements.txt
          #dvc remote modify myremote --local gdrive_user_credentials_file .dvc/tmp/gdrive-user-credentials.json
          # Pull latest data from remote
          dvc pull

          # Reproduce pipeline if any changes detected in the dependencies
          dvc repro Training
